services:
  todo:
    container_name: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/usr/src:cache
    ports:
      - 8080:8080
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Sa01
      POSTGRES_DB: todo
    ports:
      - 5432:5432